USE Ql_DATHANG_BANHANG
GO

--Khách hàng xem tình trạng đơn hàng
CREATE PROCEDURE USP_KIEMTRA_TTGH_FIX @MA_KHACH_HANG CHAR(5), @MA_DON CHAR(5)
AS
BEGIN TRAN
	SET TRAN ISOLATION LEVEL REPEATABLE READ
	IF NOT EXISTS(SELECT DDH.* FROM DONDATHANG DDH WHERE DDH.MA_KHACH_HANG=@MA_KHACH_HANG AND DDH.MA_DON=@MA_DON)
	BEGIN
		PRINT N'ĐH không tồn tại'
		RETURN
	END

	DECLARE @TTGH NVARCHAR(255)
	SET @TTGH = 0
	SET @TTGH = (SELECT TINH_TRANG FROM DONDATHANG WHERE MA_DON = @MA_DON)
	WAITFOR DELAY '00:00:05'

	IF ((SELECT  TINH_TRANG FROM DONDATHANG WHERE MA_DON = @MA_DON) <> @TTGH)
	BEGIN
		RAISERROR(N'Dữ liệu hai lần đọc khác nhau',16,1)
	END
	SELECT *
	FROM DONDATHANG
	WHERE MA_DON = @MA_DON
COMMIT TRAN
GO


--Tài xế thực hiện cập nhật tình trạng đơn hàng 
CREATE PROCEDURE USP_TX_CAPNHAT_TTGH_FIX @MA_TAI_XE CHAR(5), @MA_DON CHAR(5), @TTGH NVARCHAR(255)
AS
BEGIN TRAN
	UPDATE DONDATHANG
	SET TINH_TRANG = @TTGH
	WHERE MA_DON = @MA_DON AND MA_TAI_XE = @MA_TAI_XE
COMMIT TRAN