-- ĐỐI TÁC CẬP NHẬP GIÁ MÓN ĂN
CREATE
PROC SP_CAPNHAPGIAMONAN 
		@MAMONAN CHAR(5),
		@MACH CHAR(5),
		@GIAMOI FLOAT
AS
BEGIN TRAN
	BEGIN TRY
			IF NOT EXISTS(SELECT * FROM MON_AN
									WHERE @MAMONAN=MA_MON_AN
									AND @MACH=MA_CUA_HANG)
			BEGIN
				PRINT N'KHÔNG TỒN TẠI MÓN ĂN'
				ROLLBACK TRAN
				RETURN 1
			END

			UPDATE MON_AN
			SET DON_GIA=@GIAMOI
			WHERE @MAMONAN=MA_MON_AN AND @MACH=MA_CUA_HANG

			-- TEST
			WAITFOR DELAY '0:0:20'

			IF @GIAMOI=0
			BEGIN
				ROLLBACK TRAN
				RETURN 1
			END

	END TRY
	BEGIN CATCH
		PRINT N'ERROR'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

--KHÁCH HÀNG XEM MÓN ĂN
CREATE
PROC SP_XEMMONAN @MAMONAN CHAR(5)
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
		BEGIN TRY
			SELECT MA.MA_MON_AN, MA.TEN_MON, MA.DON_GIA, CH.TEN_CUA_HANG, MA.TINH_TRANG, MA.TRANG_THAI
			FROM MON_AN MA, CUAHANG CH
			WHERE MA.MA_MON_AN=@MAMONAN 
			AND MA.MA_CUA_HANG=CH.MA_CUA_HANG
		END TRY
		BEGIN CATCH
			PRINT N'ERROR'
			ROLLBACK TRAN
		END CATCH
COMMIT TRAN
GO

