USE Ql_DATHANG_BANHANG


--Cửa hàng được xem, xóa, chỉnh sửa, cập nhật thông tin của cửa hàng, thực đơn, món ăn 
GRANT INSERT,SELECT,UPDATE,DELETE ON CUAHANG TO NHAHANG
GRANT INSERT,SELECT,UPDATE,DELETE ON THUCDON TO NHAHANG
GRANT INSERT,SELECT,UPDATE,DELETE ON MON_AN TO NHAHANG

--cửa hàng được xem đơn hàng, chi tiết đơn hàng, thông tin tài xế, thông tin hợp đồng, thông tin các chi nhánh
GRANT SELECT ON DONDATHANG TO NHAHANG WITH GRANT OPTION
GRANT SELECT ON CHITIET_DONHANG TO NHAHANG WITH GRANT OPTION
GRANT SELECT ON TAIXE TO NHAHANG WITH GRANT OPTION
GRANT SELECT ON KHACHHANG TO NHAHANG WITH GRANT OPTION
GRANT SELECT ON HOPDONG TO NHAHANG WITH GRANT OPTION
GRANT SELECT ON CHINHANH TO NHAHANG WITH GRANT OPTION
-- cửa hàng được phép sửa địa chỉ của chi nhánh
GRANT UPDATE ON CHINHANH(DIA_CHI,KHUVUC) TO NHAHANG

-- cửa hàng được phép thêm chi nhánh
GRANT INSERT ON CHINHANH TO NHAHANG


-- tài xế được thêm, xem, cập nhật, xóa thông tin tài xế 
GRANT INSERT,SELECT,UPDATE,DELETE ON TAIXE TO TAIXE
--tài xế được cập nhật tình trạng đơn hàng
GRANT UPDATE ON DONDATHANG(TINH_TRANG) TO TAIXE

--Phân hệ khách hàng
-- Khách hàng có thể thêm, update, select, delete trên thông tin của chính khách hàng

GRANT INSERT, UPDATE, SELECT, DELETE ON KHACHHANG TO KHACHHANG 
-- Khách hàng có thể xem danh sách các chi nhánh, cửa hàng, tài xế, thực đơn, thông tin món ăn, đơn đặt hàng
GRANT SELECT ON CHINHANH TO KHACHHANG
GRANT SELECT ON CUAHANG TO KHACHHANG
GRANT SELECT ON TAIXE TO KHACHHANG
GRANT SELECT ON THUCDON TO KHACHHANG
GRANT SELECT ON MON_AN TO KHACHHANG
GRANT SELECT ON DONDATHANG TO KHACHHANG

-- Nhân viên có thể xem và sửa đổi đơn đặt hàng
GRANT SELECT, UPDATE ON HOPDONG TO NHANVIEN

-- Nhân viên có thể xem thông tin cửa hàng
GRANT SELECT ON CUAHANG TO NHANVIEN


-- Quản trị có thể thêm, xóa, sửa trên tất cả bảng
GRANT INSERT, DELETE, UPDATE ON CHINHANH TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON CHITIET_DONHANG TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON CUAHANG TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON DONDATHANG TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON HOPDONG TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON KHACHHANG TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON MON_AN TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON TAIXE TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON THUCDON TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON THUCDON_MONAN TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON TKNGANHANG TO QUANTRI WITH GRANT OPTION AS QUANTRI
GRANT INSERT, DELETE, UPDATE ON TUYCHON TO QUANTRI WITH GRANT OPTION AS QUANTRI

--phân quyền cho các procedure


GRANT EXECUTE on OBJECT::SP_KHACH_HANG_DAT_HANG_MON_AN to KHACHHANG
GRANT EXECUTE ON OBJECT::sp_KH_XemDSDoiTac to KHACHHANG
GRANT EXECUTE ON OBJECT::sp_KH_xem_MonAN to KHACHHANG
GRANT EXECUTE on OBJECT::sp_DT_ThemChiNhanh TO NHAHANG
GRANT EXECUTE on OBJECT::USP_KH_XEMGIA_MONAN to KHACHHANG
GRANT EXECUTE on OBJECT::USP_DT_CAPNHAT_GIA_MONAN to NHAHANG
GRANT EXECUTE on OBJECT::SP_CH_CAP_NHAT_SL_MON_AN to NHAHANG
GRANT EXECUTE on OBJECT::USP_QT2_CAPNHAT_TT to QUANTRI
GRANT EXECUTE on OBJECT::USP_QT1_CAPNHAT_TT to QUANTRI
GRANT EXECUTE on OBJECT::gia_han_hop_dong to NHANVIEN
GRANT EXECUTE on OBJECT::SP_ThongTinChiNhanh_Ma to NHANVIEN

