USE Ql_DATHANG_BANHANG
GO

--Người quản trị 1 cập nhật thông tin tài khoản của khách hàng (đổi mật khẩu) và cập nhật thông tin của tài xế (Email).

CREATE PROCEDURE USP_QT1_CAPNHAT_TT @TEN_DANG_NHAP NVARCHAR(255), @MAT_KHAU_MOI CHAR(100), @MATX CHAR(5), @EMAIL_MOI CHAR(100)
AS
BEGIN TRAN
	IF NOT EXISTS(SELECT TK.* FROM TAIKHOAN TK WHERE TEN_DANG_NHAP=@TEN_DANG_NHAP)
	BEGIN
		PRINT N'Tài khoản không tồn tại'
		RETURN
	END


	UPDATE TAIKHOAN SET MAT_KHAU = @MAT_KHAU_MOI WHERE TEN_DANG_NHAP=@TEN_DANG_NHAP
	WAITFOR DELAY '00:00:05'

	UPDATE TAIXE
	SET EMAIL = @EMAIL_MOI
	WHERE MA_TAI_XE = @MATX
COMMIT TRAN
GO


--Quản trị 2 cập nhật thông tin của tài xế(Email) và cập nhật thông tin tài khoản của khách hàng (đổi mật khẩu).
CREATE PROCEDURE USP_QT2_CAPNHAT_TT @TEN_DANG_NHAP NVARCHAR(255), @MAT_KHAU_MOI CHAR(100), @MATX CHAR(5), @EMAIL_MOI CHAR(100)
AS
BEGIN TRAN
	IF NOT EXISTS(SELECT TK.* FROM TAIKHOAN TK WHERE TEN_DANG_NHAP=@TEN_DANG_NHAP)
	BEGIN
		PRINT N'Tài khoản không tồn tại'
		RETURN
	END

	UPDATE TAIXE
	SET EMAIL = @EMAIL_MOI
	WHERE MA_TAI_XE = @MATX
	WAITFOR DELAY '00:00:05'

	UPDATE TAIKHOAN SET MAT_KHAU = @MAT_KHAU_MOI WHERE TEN_DANG_NHAP=@TEN_DANG_NHAP
COMMIT TRAN
GO