USE Ql_DATHANG_BANHANG_HQTCSDL
GO
--LOST UPDATED
-- ĐỐI TÁC CẬP NHẬT SỐ LƯỢNG MÓN ĂN TẠI MÔT CHI NHÀNH
-- KHÁCH HÀNG MUA HÀNG TẠI MỘT CHI NHÁNH VỚI SỐ LƯỢNG NHẤT ĐỊNH
GO

-- ĐỐI TÁC CẬP NHẬT SỐ LƯỢNG MÓN ĂN TẠI MÔT CHI NHÀNH

CREATE 
--alter 
PROC SP_CH_CAP_NHAT_SL_MON_AN
	@MA_CHI_NHANH CHAR(5),
	@MA_MON_AN CHAR(5),
	@SO_LUONG_THEM INT
AS
     SET TRANSACTION ISOLATION LEVEL READ COMMITTED

	BEGIN TRAN
	    
		IF NOT EXISTS (SELECT * FROM MON_AN_CHI_NHANH MA_CN WHERE MA_CHI_NHANH = @MA_CHI_NHANH AND MA_MON_AN = @MA_MON_AN) --(1)
			BEGIN	
				PRINT @MA_CHI_NHANH +', '+@MA_MON_AN + N' KHÔNG HỢP LỆ !'
				ROLLBACK TRAN
				RETURN 0
			END

		IF @SO_LUONG_THEM <1
			BEGIN	
				PRINT N'SỐ LƯỢNG THÊM KHÔNG HỢP LỆ !'
				ROLLBACK TRAN
				RETURN 0
			END
		DECLARE @SO_LUONG_HIEN_CO INT --100
		SET @SO_LUONG_HIEN_CO = ( SELECT SO_LUONG FROM MON_AN_CHI_NHANH WHERE MA_CHI_NHANH = @MA_CHI_NHANH AND MA_MON_AN = @MA_MON_AN )
		IF @SO_LUONG_HIEN_CO <1
			BEGIN	
				PRINT ' SỐ LƯỢNG HIỆN CÓ KHÔNG HỢP LỆ !'
				ROLLBACK TRAN
				RETURN 0
			END

		WAITFOR DELAY '00:00:10' 

		UPDATE MON_AN_CHI_NHANH --(4)
		SET SO_LUONG = @SO_LUONG_HIEN_CO + @SO_LUONG_THEM --(100 + 100)
		WHERE MA_CHI_NHANH = @MA_CHI_NHANH AND MA_MON_AN = @MA_MON_AN
	COMMIT TRAN
PRINT N'CẬP NHẬT THÀNH CÔNG'
RETURN 1

GO

-- KHÁCH HÀNG ĐẶT HÀNG MÓN ĂN TẠI MỘT CHI NHÁNH VỚI SỐ LƯỢNG NHẤT ĐỊNH
CREATE PROC SP_KHACH_HANG_DAT_HANG_MON_AN -- 10
	@MA_DON CHAR(5),
	@MA_MON_AN CHAR(5),
	@SO_LUONG INT,
	@DIA_CHI NVARCHAR(255),
	@PHI_VAN_CHUYEN FLOAT,
	@MA_KHACH_HANG CHAR(5),
	@MA_CHI_NHANH CHAR(5)

AS
 SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRAN
		-- KIỂM TRA THÔNG TIN ĐẦU VÀO 
		IF( @PHI_VAN_CHUYEN IS NULL OR @DIA_CHI IS NULL OR @SO_LUONG IS NULL )
			BEGIN	
				PRINT N' THÔNG TIN (PHÍ VẬN CHUYỂN | ĐỊA CHỈ | SỐ LƯỢNG ) NULL'
				ROLLBACK TRAN
				RETURN 0
			END
		IF( @MA_KHACH_HANG NOT IN( SELECT MA_KHACH_HANG FROM KHACHHANG) OR
			@MA_CHI_NHANH NOT IN( SELECT MA_CHI_NHANH FROM CHINHANH))
			BEGIN	
				PRINT N'KHÔNG TỒN TẠI ' + @MA_KHACH_HANG  +N' HOẶC '+ @MA_CHI_NHANH
				ROLLBACK TRAN
				RETURN 0
			END
		
		IF( @MA_MON_AN NOT IN ( SELECT MA_MON_AN FROM MON_AN WHERE TINH_TRANG = N'có bán'))
			BEGIN	
				PRINT @MA_MON_AN + N' KHÔNG TỒN TẠI'
				ROLLBACK TRAN
				RETURN 0
			END
		IF (@SO_LUONG > ( SELECT A.SO_LUONG FROM MON_AN_CHI_NHANH A WHERE A.MA_CHI_NHANH = @MA_CHI_NHANH AND A.MA_MON_AN =@MA_MON_AN)) --(2)
			BEGIN	
				PRINT N'SỐ LƯỢNG HIỆN TẠI CỦA CHI NHÁNH '+ @MA_CHI_NHANH+' KHÔNG ĐỦ ĐÁP ỨNG'
				ROLLBACK TRAN
				RETURN 0
			END
		DECLARE @DON_GIA_MON FLOAT
		SET @DON_GIA_MON  = (SELECT DON_GIA FROM MON_AN WHERE MA_MON_AN = @MA_MON_AN )

		DECLARE @TONG_TIEN FLOAT 
		SET @TONG_TIEN = @DON_GIA_MON * @SO_LUONG
		
		-- INSERT DON DAT HÀNG
		IF( EXISTS ( SELECT * FROM DONDATHANG DH WHERE DH.MA_DON = @MA_DON))
			BEGIN	
					INSERT INTO CHITIET_DONHANG VALUES(@MA_DON , @MA_MON_AN,@SO_LUONG,@TONG_TIEN)
			END
		else
			begin
				INSERT INTO DONDATHANG VALUES(@MA_DON,@TONG_TIEN,@DIA_CHI,N'chờ xác nhận',@PHI_VAN_CHUYEN,@MA_KHACH_HANG,null,@MA_CHI_NHANH,1)
			-- INSERT CHI TIẾT ĐƠN HÀNG 
				INSERT INTO CHITIET_DONHANG VALUES(@MA_DON , @MA_MON_AN,@SO_LUONG,@TONG_TIEN)
			-- CẬP NHẬT SỐ LƯỢNG MÓN TẠI CHI NHÁNH
			end
		UPDATE MON_AN_CHI_NHANH 
		SET SO_LUONG = SO_LUONG - @SO_LUONG --(3)
		WHERE @MA_CHI_NHANH = MA_CHI_NHANH AND @MA_MON_AN = MA_MON_AN
	COMMIT TRAN
	PRINT N'CẬP NHẬT THÀNH CÔNG'
RETURN 1
GO
