USE Ql_DATHANG_BANHANG_HQTCSDL
GO

EXEC SP_CH_CAP_NHAT_SL_MON_AN 'CN001','MA003',60

select * from MON_AN_CHI_NHANH where MA_CHI_NHANH = 'CN001' and MA_MON_AN = 'MA003'


select * from MON_AN_CHI_NHANH